<?php

namespace Gt\SistemaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * empresaUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class empresaUsuarioRepository extends EntityRepository
{
    public function getEmpresaListaUsuario($p)
    {          
        $em = $this->getEntityManager(); 
        $sql = "SELECT A.empresa_id , B.empresaRut , B.empresaRazonSocial,  A.empresaUsuarioDefault
                FROM empresaUsuario A 
                LEFT JOIN empresa B ON A.empresa_id=B.id
                WHERE A.id_usuario=".$p['idUsuario'].
                " AND A.empresa_id NOT IN ( 0,1 )
                GROUP BY B.empresaRut 
                ORDER BY 3 asc
                "
                ;
//        echo "<br>[$sql]";
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    
    public function getEmpresaListaUsuarioConDemo($p){
        $em = $this->getEntityManager(); 
        $sql = "SELECT A.empresa_id , B.empresaRut , B.empresaRazonSocial,  A.empresaUsuarioDefault
                FROM empresaUsuario A 
                LEFT JOIN empresa B ON A.empresa_id=B.id
                WHERE A.id_usuario=".$p['idUsuario']."
                GROUP BY B.empresaRut 
                ORDER BY 3 asc
                "
                ;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
