security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
#        Gt\SistemaBundle\Entity\usuario:
#            algorithm:        sha1  
#            encode_as_base64: false
#            iterations:       1

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
#        user_db:
#            entity: { class: Gt\SistemaBundle\Entity\usuario, property: username }

#    firewalls:
#        main:
#            pattern: /.*
#            provider: user_db
#            form_login:
#                login_path: /login
#                check_path: /login_check
#                remember_me: true
#                always_use_default_target_path: true
#                default_target_path: /inicio
#            logout:
#                path: /logout
#                target: /login
#            remember_me:
#                key: 0123456789
#                lifetime: 13600
#                path: /.*
#                domain: ~
#            security: true
#            anonymous: true

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                default_target_path: /inicio
            logout:       
                path: /logout
                target: /
            anonymous:    true
            
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/logoutsession, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/.*, roles: ROLE_USER }
        
