<?php

namespace Proxies\__CG__\Gt\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class evaluacionActividadClave extends \Gt\SistemaBundle\Entity\evaluacionActividadClave implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'participanteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'actividadClaveId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'evaluacionActividadClaveRespuesta', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'evaluacionCriterios');
        }

        return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'participanteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'actividadClaveId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'evaluacionActividadClaveRespuesta', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionActividadClave' . "\0" . 'evaluacionCriterios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (evaluacionActividadClave $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipanteId($participanteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipanteId', array($participanteId));

        return parent::setParticipanteId($participanteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipanteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipanteId', array());

        return parent::getParticipanteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setActividadClaveId($actividadClaveId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividadClaveId', array($actividadClaveId));

        return parent::setActividadClaveId($actividadClaveId);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadClaveId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadClaveId', array());

        return parent::getActividadClaveId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluacionActividadClaveRespuesta($evaluacionActividadClaveRespuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluacionActividadClaveRespuesta', array($evaluacionActividadClaveRespuesta));

        return parent::setEvaluacionActividadClaveRespuesta($evaluacionActividadClaveRespuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluacionActividadClaveRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluacionActividadClaveRespuesta', array());

        return parent::getEvaluacionActividadClaveRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluacionCriterios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluacionCriterios', array());

        return parent::getEvaluacionCriterios();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvaluacionCriterio(\Gt\SistemaBundle\Entity\evaluacionCriterio $evaluacionCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvaluacionCriterio', array($evaluacionCriterio));

        return parent::addEvaluacionCriterio($evaluacionCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvaluacionCriterio(\Gt\SistemaBundle\Entity\evaluacionCriterio $evaluacionCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvaluacionCriterio', array($evaluacionCriterio));

        return parent::removeEvaluacionCriterio($evaluacionCriterio);
    }

}
