<?php

namespace Proxies\__CG__\Gt\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class usuario extends \Gt\SistemaBundle\Entity\usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'username', 'email', 'usuarioMail', 'salt', 'password', 'usuarioClave', 'isActive', 'roles', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioNombre', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioApellidos', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioRut', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'idPerfilempresa', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'idUsuarioTipo');
        }

        return array('__isInitialized__', 'id', 'username', 'email', 'usuarioMail', 'salt', 'password', 'usuarioClave', 'isActive', 'roles', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioNombre', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioApellidos', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'usuarioRut', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'idPerfilempresa', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\usuario' . "\0" . 'idUsuarioTipo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariomail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariomail', array($email));

        return parent::setUsuariomail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariomail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariomail', array());

        return parent::getUsuariomail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioClave($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioClave', array($password));

        return parent::setUsuarioClave($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioClave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioClave', array());

        return parent::getUsuarioClave();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($active));

        return parent::setIsActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole(\Gt\SistemaBundle\Entity\Rol $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($roles));

        return parent::addRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\Gt\SistemaBundle\Entity\Rol $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($roles));

        return parent::removeRole($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function isEqualTo(\Symfony\Component\Security\Core\User\UserInterface $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEqualTo', array($user));

        return parent::isEqualTo($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioNombre', array($nombre));

        return parent::setUsuarioNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioNombre', array());

        return parent::getUsuarioNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioapellidos($apellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioapellidos', array($apellido));

        return parent::setUsuarioapellidos($apellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioapellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioapellidos', array());

        return parent::getUsuarioapellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuariorut($rut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuariorut', array($rut));

        return parent::setUsuariorut($rut);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariorut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariorut', array());

        return parent::getUsuariorut();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPerfilempresa($idPerfilempresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPerfilempresa', array($idPerfilempresa));

        return parent::setIdPerfilempresa($idPerfilempresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPerfilempresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPerfilempresa', array());

        return parent::getIdPerfilempresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuarioTipo($idUsuarioTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuarioTipo', array($idUsuarioTipo));

        return parent::setIdUsuarioTipo($idUsuarioTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuarioTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuarioTipo', array());

        return parent::getIdUsuarioTipo();
    }

}
