<?php

namespace Proxies\__CG__\Gt\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class evaluacionCriterio extends \Gt\SistemaBundle\Entity\evaluacionCriterio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'evaluacionActividadClaveId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'participanteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'criterioId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'evaluacionCriterioRespuesta');
        }

        return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'evaluacionActividadClaveId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'participanteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'criterioId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\evaluacionCriterio' . "\0" . 'evaluacionCriterioRespuesta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (evaluacionCriterio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaId($empresaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaId', array($empresaId));

        return parent::setEmpresaId($empresaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaId', array());

        return parent::getEmpresaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluacionActividadClaveId($evaluacionActividadClaveId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluacionActividadClaveId', array($evaluacionActividadClaveId));

        return parent::setEvaluacionActividadClaveId($evaluacionActividadClaveId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluacionActividadClaveId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluacionActividadClaveId', array());

        return parent::getEvaluacionActividadClaveId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParticipanteId($participanteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParticipanteId', array($participanteId));

        return parent::setParticipanteId($participanteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipanteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipanteId', array());

        return parent::getParticipanteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriterioId($criterioId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriterioId', array($criterioId));

        return parent::setCriterioId($criterioId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriterioId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriterioId', array());

        return parent::getCriterioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluacionCriterioRespuesta($evaluacionCriterioRespuesta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluacionCriterioRespuesta', array($evaluacionCriterioRespuesta));

        return parent::setEvaluacionCriterioRespuesta($evaluacionCriterioRespuesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvaluacionCriterioRespuesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvaluacionCriterioRespuesta', array());

        return parent::getEvaluacionCriterioRespuesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvaluacionActividadClave(\Gt\SistemaBundle\Entity\evaluacionActividadClave $evaluacionActividadClave = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvaluacionActividadClave', array($evaluacionActividadClave));

        return parent::setEvaluacionActividadClave($evaluacionActividadClave);
    }

}
