<?php

namespace Proxies\__CG__\Gt\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class clienteCompetencia extends \Gt\SistemaBundle\Entity\clienteCompetencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'empresaId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaCodigo', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaNombre', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaDefinicion');
        }

        return array('__isInitialized__', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'id', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'empresaId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteId', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaCodigo', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaNombre', '' . "\0" . 'Gt\\SistemaBundle\\Entity\\clienteCompetencia' . "\0" . 'clienteCompetenciaDefinicion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (clienteCompetencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaId($empresaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaId', array($empresaId));

        return parent::setEmpresaId($empresaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaId', array());

        return parent::getEmpresaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteId($clienteId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteId', array($clienteId));

        return parent::setClienteId($clienteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteId', array());

        return parent::getClienteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteCompetenciaCodigo($clienteCompetenciaCodigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteCompetenciaCodigo', array($clienteCompetenciaCodigo));

        return parent::setClienteCompetenciaCodigo($clienteCompetenciaCodigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteCompetenciaCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteCompetenciaCodigo', array());

        return parent::getClienteCompetenciaCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteCompetenciaNombre($clienteCompetenciaNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteCompetenciaNombre', array($clienteCompetenciaNombre));

        return parent::setClienteCompetenciaNombre($clienteCompetenciaNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteCompetenciaNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteCompetenciaNombre', array());

        return parent::getClienteCompetenciaNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setClienteCompetenciaDefinicion($clienteCompetenciaDefinicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClienteCompetenciaDefinicion', array($clienteCompetenciaDefinicion));

        return parent::setClienteCompetenciaDefinicion($clienteCompetenciaDefinicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getClienteCompetenciaDefinicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClienteCompetenciaDefinicion', array());

        return parent::getClienteCompetenciaDefinicion();
    }

}
